# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _monopod
else:
    import _monopod

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _monopod.delete_SwigPyIterator

    def value(self):
        return _monopod.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _monopod.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _monopod.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _monopod.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _monopod.SwigPyIterator_equal(self, x)

    def copy(self):
        return _monopod.SwigPyIterator_copy(self)

    def next(self):
        return _monopod.SwigPyIterator_next(self)

    def __next__(self):
        return _monopod.SwigPyIterator___next__(self)

    def previous(self):
        return _monopod.SwigPyIterator_previous(self)

    def advance(self, n):
        return _monopod.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _monopod.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _monopod.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _monopod.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _monopod.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _monopod.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _monopod.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _monopod:
_monopod.SwigPyIterator_swigregister(SwigPyIterator)

SHARED_PTR_DISOWN = _monopod.SHARED_PTR_DISOWN
class VectorOfModels(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _monopod.VectorOfModels_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _monopod.VectorOfModels___nonzero__(self)

    def __bool__(self):
        return _monopod.VectorOfModels___bool__(self)

    def __len__(self):
        return _monopod.VectorOfModels___len__(self)

    def __getslice__(self, i, j):
        return _monopod.VectorOfModels___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _monopod.VectorOfModels___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _monopod.VectorOfModels___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _monopod.VectorOfModels___delitem__(self, *args)

    def __getitem__(self, *args):
        return _monopod.VectorOfModels___getitem__(self, *args)

    def __setitem__(self, *args):
        return _monopod.VectorOfModels___setitem__(self, *args)

    def pop(self):
        return _monopod.VectorOfModels_pop(self)

    def append(self, x):
        return _monopod.VectorOfModels_append(self, x)

    def empty(self):
        return _monopod.VectorOfModels_empty(self)

    def size(self):
        return _monopod.VectorOfModels_size(self)

    def swap(self, v):
        return _monopod.VectorOfModels_swap(self, v)

    def begin(self):
        return _monopod.VectorOfModels_begin(self)

    def end(self):
        return _monopod.VectorOfModels_end(self)

    def rbegin(self):
        return _monopod.VectorOfModels_rbegin(self)

    def rend(self):
        return _monopod.VectorOfModels_rend(self)

    def clear(self):
        return _monopod.VectorOfModels_clear(self)

    def get_allocator(self):
        return _monopod.VectorOfModels_get_allocator(self)

    def pop_back(self):
        return _monopod.VectorOfModels_pop_back(self)

    def erase(self, *args):
        return _monopod.VectorOfModels_erase(self, *args)

    def __init__(self, *args):
        _monopod.VectorOfModels_swiginit(self, _monopod.new_VectorOfModels(*args))

    def push_back(self, x):
        return _monopod.VectorOfModels_push_back(self, x)

    def front(self):
        return _monopod.VectorOfModels_front(self)

    def back(self):
        return _monopod.VectorOfModels_back(self)

    def assign(self, n, x):
        return _monopod.VectorOfModels_assign(self, n, x)

    def resize(self, *args):
        return _monopod.VectorOfModels_resize(self, *args)

    def insert(self, *args):
        return _monopod.VectorOfModels_insert(self, *args)

    def reserve(self, n):
        return _monopod.VectorOfModels_reserve(self, n)

    def capacity(self):
        return _monopod.VectorOfModels_capacity(self)
    __swig_destroy__ = _monopod.delete_VectorOfModels

# Register VectorOfModels in _monopod:
_monopod.VectorOfModels_swigregister(VectorOfModels)

import scenario.bindings.core
class Joint(scenario.bindings.core.Joint):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _monopod.Joint_swiginit(self, _monopod.new_Joint())
    __swig_destroy__ = _monopod.delete_Joint

    def id(self):
        return _monopod.Joint_id(self)

    def initialize(self, _name, _model_name):
        return _monopod.Joint_initialize(self, _name, _model_name)

    def valid(self):
        r"""
        Check if the joint is valid.

        :rtype: boolean
        :return: True if the model is valid, false otherwise.
        """
        return _monopod.Joint_valid(self)

    def dofs(self):
        r"""
        Get the number of degrees of freedom of the joint.

        :rtype: int
        :return: The number of DOFs of the joint.
        """
        return _monopod.Joint_dofs(self)

    def name(self, scoped=False):
        r"""
        Get the name of the joint.

        :type scoped: boolean
        :param scoped: If true, the scoped name of the joint is returned.
        :rtype: string
        :return: The name of the joint.
        """
        return _monopod.Joint_name(self, scoped)

    def type(self):
        r"""
        Get the type of the joint.

        :rtype: int
        :return: The type of the joint.
        """
        return _monopod.Joint_type(self)

    def set_control_mode(self, mode):
        r"""
        Set the joint control mode.

        :type mode: int
        :param mode: The desired control mode.
        :rtype: boolean
        :return: True for success, false otherwise.
        """
        return _monopod.Joint_set_control_mode(self, mode)

    def control_mode(self):
        r"""
        get the joint control mode.

        :rtype: int
        :return: the joint control mode
        """
        return _monopod.Joint_control_mode(self)

    def pid(self):
        r"""
        Get the PID parameters of the joint.

        If no PID parameters have been set, the default parameters are
        returned.

        :rtype: :py:class:`PID`
        :return: The joint PID parameters.
        """
        return _monopod.Joint_pid(self)

    def set_pid(self, pid):
        r"""
        Set the PID parameters of the joint.

        :type pid: :py:class:`PID`
        :param pid: The desired PID parameters.
        :rtype: boolean
        :return: True for success, false otherwise.
        """
        return _monopod.Joint_set_pid(self, pid)

    def joint_max_generalized_force(self):
        r"""
        Get the maximum generalized force that could be applied to the joint.

        :rtype: Tuple[float]
        :return: The maximum generalized force of the joint.
        """
        return _monopod.Joint_joint_max_generalized_force(self)

    def set_joint_max_generalized_force(self, max_force):
        r"""
        Set the maximum generalized force that can be applied to the joint.

        This limit can be used to clip the force applied by joint
        controllers.

        :type maxForce: Tuple[float]
        :param maxForce: A vector with the maximum generalized forces of the
            joint DOFs.
        :rtype: boolean
        :return: True for success, false otherwise.
        """
        return _monopod.Joint_set_joint_max_generalized_force(self, max_force)

    def joint_position(self):
        r"""
        Get the position of the joint.

        :rtype: Tuple[float]
        :return: The position of the joint.
        """
        return _monopod.Joint_joint_position(self)

    def joint_velocity(self):
        r"""
        Get the velocity of the joint.

        :rtype: Tuple[float]
        :return: The velocity of the joint.
        """
        return _monopod.Joint_joint_velocity(self)

    def joint_acceleration(self):
        r"""
        Get the acceleration of the joint.

        :rtype: Tuple[float]
        :return: The acceleration of the joint.
        """
        return _monopod.Joint_joint_acceleration(self)

    def set_joint_generalized_force_target(self, force):
        r"""
        Set the generalized force target of the joint.

        Note that if there's friction or other loss components, the real
        joint force will differ.

        :type force: Tuple[float]
        :param force: A vector with the generalized force targets of the joint
            DOFs.
        :rtype: boolean
        :return: True for success, false otherwise.
        """
        return _monopod.Joint_set_joint_generalized_force_target(self, force)

    def joint_generalized_force_target(self):
        r"""
        Get the active generalized force target.

        :rtype: Tuple[float]
        :return: The generalized force target of the joint.
        """
        return _monopod.Joint_joint_generalized_force_target(self)

# Register Joint in _monopod:
_monopod.Joint_swigregister(Joint)

class Model(scenario.bindings.core.Model):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _monopod.Model_swiginit(self, _monopod.new_Model())
    __swig_destroy__ = _monopod.delete_Model

    def id(self):
        return _monopod.Model_id(self)

    def valid(self):
        r"""
        Check if the model is valid.

        :rtype: boolean
        :return: True if the model is valid, false otherwise.
        """
        return _monopod.Model_valid(self)

    def name(self):
        r"""
        Get the name of the model.

        :rtype: string
        :return: The name of the model.
        """
        return _monopod.Model_name(self)

    def dofs(self, *args):
        return _monopod.Model_dofs(self, *args)

    def get_joint(self, joint_name):
        r"""
        Get a joint belonging to the model.

        :type jointName: string
        :param jointName: The name of the joint.
        :raises: std::runtime_error if the joint does not exist.
        :rtype: :py:class:`Joint`
        :return: The desired joint.
        """
        return _monopod.Model_get_joint(self, joint_name)

    def joint_names(self, scoped=False):
        r"""
        Get the name of all the model's joints.

        :type scoped: boolean
        :param scoped: Scope the joint names with the model name,
            (e.g. ``mymodel::joint1``).
        :rtype: Tuple[string]
        :return: The list of joint names.
        """
        return _monopod.Model_joint_names(self, scoped)

    def joint_positions(self, *args):
        r"""
        Get the joint positions.

        :type jointNames: Tuple[string]
        :param jointNames: Optional vector of considered joints that also
            defines the joint serialization. By default, ``Model::jointNames`` is
            used.
        :rtype: Tuple[float]
        :return: The serialization of joint positions. The vector has as many
            elements as DoFs of the considered joints.
        """
        return _monopod.Model_joint_positions(self, *args)

    def joint_velocities(self, *args):
        r"""
        Get the joint velocities.

        :type jointNames: Tuple[string]
        :param jointNames: Optional vector of considered joints that also
            defines the joint serialization. By default, ``Model::jointNames`` is
            used.
        :rtype: Tuple[float]
        :return: The serialization of joint velocities. The vector has as many
            elements as DoFs of the considered joints.
        """
        return _monopod.Model_joint_velocities(self, *args)

    def joint_accelerations(self, *args):
        r"""
        Get the joint accelerations.

        :type jointNames: Tuple[string]
        :param jointNames: Optional vector of considered joints that also
            defines the joint serialization. By default, ``Model::jointNames`` is
            used.
        :rtype: Tuple[float]
        :return: The serialization of joint accelerations. The vector has as many
            elements as DoFs of the considered joints.
        """
        return _monopod.Model_joint_accelerations(self, *args)

    def set_joint_control_mode(self, *args):
        r"""
        Set the control mode of model joints.

        :type mode: int
        :param mode: The desired joint control mode.
        :type jointNames: Tuple[string]
        :param jointNames: Optional vector of considered joints that also
            defines the joint serialization. By default, ``Model::jointNames`` is
            used.
        :rtype: boolean
        :return: True for success, false otherwise.
        """
        return _monopod.Model_set_joint_control_mode(self, *args)

    def joints(self, *args):
        r"""
        Get the joints of the model.

        :type jointNames: Tuple[string]
        :param jointNames: Optional vector of considered joints. By default,
            ``Model::jointNames`` is used.
        :rtype: Tuple[Joint]
        :return: A vector of pointers to the joint objects.
        """
        return _monopod.Model_joints(self, *args)

    def set_joint_generalized_force_targets(self, *args):
        r"""
        Set the generalized force targets of the joints.

        :type forces: Tuple[float]
        :param forces: The vector with the joint generalized force targets. It
            must have as many elements as the considered joint DoFs.
        :type jointNames: Tuple[string]
        :param jointNames: Optional vector of considered joints. By default,
            ``Model::jointNames`` is used.
        :rtype: boolean
        :return: True for success, false otherwise.
        """
        return _monopod.Model_set_joint_generalized_force_targets(self, *args)

    def joint_generalized_force_targets(self, *args):
        r"""
        Get the generalized force targets of the joints.

        :type jointNames: Tuple[string]
        :param jointNames: Optional vector of considered joints. By default,
            ``Model::jointNames`` is used.
        :rtype: Tuple[float]
        :return: The generalized force targets of the joints.
        """
        return _monopod.Model_joint_generalized_force_targets(self, *args)

# Register Model in _monopod:
_monopod.Model_swigregister(Model)

class World(scenario.bindings.core.World):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _monopod.World_swiginit(self, _monopod.new_World())
    __swig_destroy__ = _monopod.delete_World

    def id(self):
        return _monopod.World_id(self)

    def valid(self):
        r"""
        Check if the world is valid.

        :rtype: boolean
        :return: True if the world is valid, false otherwise.
        """
        return _monopod.World_valid(self)

    def name(self):
        r"""
        Get the name of the world.

        :rtype: string
        :return: The name of the world.
        """
        return _monopod.World_name(self)

    def model_names(self):
        r"""
        Get the name of the models that are part of the world.

        :rtype: Tuple[string]
        :return: The list of model names.
        """
        return _monopod.World_model_names(self)

    def get_model(self, model_name):
        r"""
        Get a model part of the world.

        :type modelName: string
        :param modelName: The name of the model to get.
        :rtype: :py:class:`Model`
        :return: The model if it is part of the world, ``nullptr`` otherwise.
        """
        return _monopod.World_get_model(self, model_name)

    def models(self, *args):
        r"""
        Get the models of the world.

        :type modelNames: Tuple[string]
        :param modelNames: Optional vector of considered models. By default,
            ``World::modelNames`` is used.
        :rtype: std::vector< scenario::core::ModelPtr,std::allocator< scenario::core::ModelPtr > >
        :return: A vector of pointers to the model objects.
        """
        return _monopod.World_models(self, *args)

# Register World in _monopod:
_monopod.World_swigregister(World)



